/scratch/user/nchopper/miniconda/miniconda3/envs/gsm_runner_testing/lib/python3.10/site-packages/aimnet2calc/__init__.py:17: UserWarning: PySisiphus is not installed. AIMNet2Pysis will not be available.
  warnings.warn('PySisiphus is not installed. AIMNet2Pysis will not be available.')
/scratch/user/nchopper/AIMNET2_pygsm_dimer/pyGSM/pyGSM/coordinate_systems/topology.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version
Traceback (most recent call last):
  File "/scratch/user/nchopper/AIMNET2_pygsm_dimer/Example_jupyter_test/test.py", line 909, in <module>
    main()
  File "/scratch/user/nchopper/AIMNET2_pygsm_dimer/Example_jupyter_test/test.py", line 374, in main
    geoms = manage_xyz.read_xyzs(inpfileq['xyzfile'])
  File "/scratch/user/nchopper/AIMNET2_pygsm_dimer/pyGSM/pyGSM/utilities/manage_xyz.py", line 55, in read_xyzs
    lines = open(filename).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'conf_continue.xyz'
